# Generated by Django 5.0.1 on 2025-10-28 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading pair symbol (e.g., BTCUSDT)', max_length=20, unique=True)),
                ('exchange', models.CharField(default='BINANCE', help_text='Exchange name', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Whether symbol is actively traded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbols',
                'db_table': 'symbols',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol', 'active'], name='symbols_symbol_acf710_idx'), models.Index(fields=['exchange', 'active'], name='symbols_exchang_7059be_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], help_text='Trade direction (LONG/SHORT)', max_length=10)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1h', help_text='Signal timeframe', max_length=5)),
                ('entry', models.DecimalField(decimal_places=8, help_text='Entry price', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('sl', models.DecimalField(decimal_places=8, help_text='Stop loss price', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stop Loss')),
                ('tp', models.DecimalField(decimal_places=8, help_text='Take profit price', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Take Profit')),
                ('confidence', models.FloatField(default=0.5, help_text='Signal confidence (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(blank=True, help_text='Signal source (e.g., bot name, indicator)', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Signal status', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata (indicators, volume, etc.)')),
                ('description', models.TextField(blank=True, help_text='Signal description or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signal expiration time', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signals', to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(help_text='Trading symbol', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signals.symbol')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'db_table': 'signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'direction', '-created_at'], name='signals_symbol__ea0816_idx'), models.Index(fields=['status', '-created_at'], name='signals_status_193550_idx'), models.Index(fields=['timeframe', '-created_at'], name='signals_timefra_5fc6f3_idx'), models.Index(fields=['-confidence', '-created_at'], name='signals_confide_2ea1e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', help_text='Subscription tier', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Subscription status', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=100, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Subscription expiration date', null=True)),
                ('user', models.OneToOneField(help_text='User associated with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='signal_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tier', 'status'], name='user_subscr_tier_f14453_idx'), models.Index(fields=['expires_at'], name='user_subscr_expires_e42bda_idx'), models.Index(fields=['stripe_customer_id'], name='user_subscr_stripe__aaa5d7_idx')],
            },
        ),
    ]
