# Generated by Django 4.2.10 on 2025-10-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_add_market_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='market_type',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='market_type',
        ),
    ]
