# Generated by Django 4.2.10 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_signal_leverage_signal_market_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='estimated_duration_hours',
            field=models.IntegerField(blank=True, help_text='Estimated time to reach target in hours', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='trading_type',
            field=models.CharField(choices=[('SCALPING', 'Scalping'), ('DAY', 'Day Trading'), ('SWING', 'Swing Trading')], default='DAY', help_text='Trading type (SCALPING/DAY/SWING)', max_length=10),
        ),
    ]
