# Generated by Django 4.2.10 on 2025-10-29 16:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0005_signal_estimated_duration_hours_signal_trading_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading pair symbol', max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], help_text='Trade direction', max_length=10)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], default='SPOT', help_text='Market type', max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, help_text='Entry price', max_digits=20)),
                ('entry_time', models.DateTimeField(blank=True, help_text='Time when position was entered', null=True)),
                ('position_size', models.DecimalField(decimal_places=8, default=100.0, help_text='Position size in USDT', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity of asset', max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, help_text='Stop loss price', max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, help_text='Take profit price', max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, help_text='Exit price', max_digits=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, help_text='Time when position was closed', null=True)),
                ('profit_loss', models.DecimalField(decimal_places=8, default=0, help_text='Profit/Loss in USDT', max_digits=20)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, default=0, help_text='Profit/Loss in percentage', max_digits=10)),
                ('leverage', models.IntegerField(blank=True, help_text='Leverage for futures trading', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Entry'), ('OPEN', 'Open'), ('CLOSED_TP', 'Closed - Take Profit Hit'), ('CLOSED_SL', 'Closed - Stop Loss Hit'), ('CLOSED_MANUAL', 'Closed - Manually'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current trade status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(help_text='Associated trading signal', on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='signals.signal')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this trade (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Trade',
                'verbose_name_plural': 'Paper Trades',
                'db_table': 'paper_trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal', 'status'], name='paper_trade_signal__5049c6_idx'), models.Index(fields=['user', 'status'], name='paper_trade_user_id_778587_idx'), models.Index(fields=['symbol', 'status'], name='paper_trade_symbol_1828e9_idx'), models.Index(fields=['-created_at'], name='paper_trade_created_a3d2b1_idx')],
            },
        ),
    ]
