# Generated by Django 4.2.10 on 2025-10-29 18:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0006_papertrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=1000.0, help_text='Starting balance in USDT', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, help_text='Available balance in USDT', max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, default=1000.0, help_text='Total equity (balance + unrealized P/L)', max_digits=12)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Total profit/loss', max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Realized profit/loss from closed trades', max_digits=12)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Unrealized P/L from open positions', max_digits=12)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_position_size', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum position size as percentage of balance', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_open_trades', models.IntegerField(default=5, help_text='Maximum number of concurrent open trades', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('auto_trading_enabled', models.BooleanField(default=False, help_text='Enable automatic trade execution on new signals')),
                ('auto_trade_spot', models.BooleanField(default=True, help_text='Auto-trade SPOT signals')),
                ('auto_trade_futures', models.BooleanField(default=True, help_text='Auto-trade FUTURES signals')),
                ('min_signal_confidence', models.DecimalField(decimal_places=2, default=0.7, help_text='Minimum signal confidence to auto-trade', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.95)])),
                ('open_positions', models.JSONField(default=list, help_text='List of currently open positions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_trade_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='User who owns this paper account', on_delete=django.db.models.deletion.CASCADE, related_name='paper_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Account',
                'verbose_name_plural': 'Paper Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
