# Generated by Django 4.2.10 on 2025-10-29 19:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0007_paperaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this backtest', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('symbols', models.JSONField(default=list, help_text='List of symbols to backtest')),
                ('timeframe', models.CharField(default='5m', help_text='e.g., 1m, 5m, 15m, 1h, 4h, 1d', max_length=10)),
                ('start_date', models.DateTimeField(help_text='Historical data start date')),
                ('end_date', models.DateTimeField(help_text='Historical data end date')),
                ('strategy_params', models.JSONField(default=dict, help_text='Strategy indicator parameters (RSI, EMA, MACD, etc.)')),
                ('initial_capital', models.DecimalField(decimal_places=8, default=Decimal('10000.00'), help_text='Starting capital in USDT', max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=8, default=Decimal('100.00'), help_text='Position size per trade in USDT', max_digits=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage', max_digits=5)),
                ('total_profit_loss', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Return on Investment %', max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage', max_digits=10)),
                ('max_drawdown_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('avg_trade_duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_profit_per_trade', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('equity_curve', models.JSONField(default=list, help_text='List of {timestamp, equity} points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbols', models.JSONField(default=list)),
                ('timeframe', models.CharField(max_length=10)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('params', models.JSONField(help_text='Strategy parameters: {rsi_period, ema_fast, ema_slow, etc.}')),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_profit_loss', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('optimization_score', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Composite score based on multiple metrics', max_digits=10)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizations', to='signals.backtestrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-optimization_score', '-win_rate'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PARAMETER_ADJUSTMENT', 'Parameter Adjustment'), ('SYMBOL_SELECTION', 'Symbol Selection'), ('TIMEFRAME_CHANGE', 'Timeframe Change'), ('RISK_ADJUSTMENT', 'Risk Management Adjustment'), ('INDICATOR_ADDITION', 'Add New Indicator'), ('INDICATOR_REMOVAL', 'Remove Indicator')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('current_params', models.JSONField(help_text='Current strategy parameters')),
                ('recommended_params', models.JSONField(help_text='Recommended new parameters')),
                ('expected_win_rate_improvement', models.DecimalField(decimal_places=2, help_text='Expected win rate increase %', max_digits=5)),
                ('expected_roi_improvement', models.DecimalField(decimal_places=2, help_text='Expected ROI increase %', max_digits=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confidence in recommendation (0-100)', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied to Strategy')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_optimizations', models.ManyToManyField(blank=True, related_name='recommendations', to='signals.strategyoptimization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('market_type', models.CharField(default='SPOT', help_text='SPOT or FUTURES', max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=8, help_text='Position size in USDT', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity of asset', max_digits=20)),
                ('leverage', models.IntegerField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('CLOSED_TP', 'Closed at Take Profit'), ('CLOSED_SL', 'Closed at Stop Loss'), ('CLOSED_MANUAL', 'Closed Manually'), ('CLOSED_END', 'Closed at End of Backtest')], max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signal_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('signal_indicators', models.JSONField(default=dict, help_text='Indicator values at signal time (RSI, MACD, etc.)')),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='signals.backtestrun')),
            ],
            options={
                'ordering': ['opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('equity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open_positions_value', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('open_trades', models.IntegerField(default=0)),
                ('peak_equity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('drawdown', models.DecimalField(decimal_places=8, max_digits=20)),
                ('drawdown_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='signals.backtestrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyoptimization',
            index=models.Index(fields=['-optimization_score'], name='signals_str_optimiz_e3091f_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyoptimization',
            index=models.Index(fields=['-win_rate'], name='signals_str_win_rat_8dd132_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyoptimization',
            index=models.Index(fields=['timeframe'], name='signals_str_timefra_5bd47b_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrecommendation',
            index=models.Index(fields=['-confidence_score'], name='signals_opt_confide_479499_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrecommendation',
            index=models.Index(fields=['status'], name='signals_opt_status_f708e0_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrecommendation',
            index=models.Index(fields=['type'], name='signals_opt_type_cdfa17_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest_run', 'opened_at'], name='signals_bac_backtes_bcb9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['symbol'], name='signals_bac_symbol_5f79e2_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['status'], name='signals_bac_status_08455a_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['-created_at'], name='signals_bac_created_a90c87_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['status'], name='signals_bac_status_dcc295_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['user', '-created_at'], name='signals_bac_user_id_3af463_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestmetric',
            index=models.Index(fields=['backtest_run', 'timestamp'], name='signals_bac_backtes_df55bc_idx'),
        ),
    ]
