# Generated by Django 4.2.10 on 2025-10-29 20:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0008_backtest_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkForwardOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('symbols', models.JSONField(default=list, help_text='List of symbols to test')),
                ('timeframe', models.CharField(default='5m', max_length=10)),
                ('start_date', models.DateTimeField(help_text='Overall start date')),
                ('end_date', models.DateTimeField(help_text='Overall end date')),
                ('training_window_days', models.IntegerField(default=90, help_text='Training period duration in days')),
                ('testing_window_days', models.IntegerField(default=30, help_text='Out-of-sample testing period in days')),
                ('step_days', models.IntegerField(default=30, help_text='How many days to roll forward each iteration')),
                ('parameter_ranges', models.JSONField(default=dict, help_text='Parameter ranges to test in optimization phase')),
                ('optimization_method', models.CharField(choices=[('grid', 'Grid Search'), ('random', 'Random Search')], default='grid', max_length=20)),
                ('initial_capital', models.DecimalField(decimal_places=8, default=Decimal('10000.00'), max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=8, default=Decimal('100.00'), max_digits=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_windows', models.IntegerField(default=0)),
                ('completed_windows', models.IntegerField(default=0)),
                ('avg_in_sample_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('avg_out_sample_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('avg_in_sample_roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_out_sample_roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('performance_degradation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% drop from in-sample to out-of-sample performance', max_digits=10)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How consistent results are across windows', max_digits=5)),
                ('is_robust', models.BooleanField(default=False, help_text='True if strategy passes robustness checks')),
                ('robustness_notes', models.TextField(blank=True, help_text='Explanation of robustness verdict', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkForwardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_number', models.IntegerField()),
                ('window_type', models.CharField(choices=[('in_sample', 'In-Sample'), ('out_sample', 'Out-of-Sample')], max_length=20)),
                ('cumulative_trades', models.IntegerField(default=0)),
                ('cumulative_pnl', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('cumulative_roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('window_trades', models.IntegerField(default=0)),
                ('window_pnl', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('window_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('walk_forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='signals.walkforwardoptimization')),
            ],
            options={
                'ordering': ['walk_forward', 'window_number', 'window_type'],
            },
        ),
        migrations.CreateModel(
            name='WalkForwardWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_number', models.IntegerField(help_text='Sequential window number')),
                ('training_start', models.DateTimeField(help_text='In-sample optimization start')),
                ('training_end', models.DateTimeField(help_text='In-sample optimization end')),
                ('testing_start', models.DateTimeField(help_text='Out-of-sample testing start')),
                ('testing_end', models.DateTimeField(help_text='Out-of-sample testing end')),
                ('in_sample_backtest_id', models.IntegerField(blank=True, null=True)),
                ('best_params', models.JSONField(default=dict, help_text='Best parameters found during optimization')),
                ('in_sample_total_trades', models.IntegerField(default=0)),
                ('in_sample_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('in_sample_roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('in_sample_sharpe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('in_sample_max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('out_sample_backtest_id', models.IntegerField(blank=True, null=True)),
                ('out_sample_total_trades', models.IntegerField(default=0)),
                ('out_sample_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('out_sample_roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('out_sample_sharpe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('out_sample_max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('performance_drop_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% performance drop from in-sample to out-of-sample', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPTIMIZING', 'Optimizing'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walk_forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='signals.walkforwardoptimization')),
            ],
            options={
                'ordering': ['walk_forward', 'window_number'],
                'indexes': [models.Index(fields=['walk_forward', 'window_number'], name='signals_wal_walk_fo_347568_idx'), models.Index(fields=['status'], name='signals_wal_status_7e8b41_idx')],
                'unique_together': {('walk_forward', 'window_number')},
            },
        ),
        migrations.AddIndex(
            model_name='walkforwardoptimization',
            index=models.Index(fields=['-created_at'], name='signals_wal_created_0ce08b_idx'),
        ),
        migrations.AddIndex(
            model_name='walkforwardoptimization',
            index=models.Index(fields=['status'], name='signals_wal_status_9bc90b_idx'),
        ),
        migrations.AddIndex(
            model_name='walkforwardoptimization',
            index=models.Index(fields=['user', '-created_at'], name='signals_wal_user_id_0aec50_idx'),
        ),
        migrations.AddIndex(
            model_name='walkforwardmetric',
            index=models.Index(fields=['walk_forward', 'window_number'], name='signals_wal_walk_fo_25aa3c_idx'),
        ),
    ]
