# Generated by Django 4.2.10 on 2025-10-29 21:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0009_walkforwardoptimization_walkforwardmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('symbols', models.JSONField(default=list, help_text='List of trading symbols')),
                ('timeframe', models.CharField(default='5m', help_text='Candle timeframe (e.g., 5m, 15m, 1h)', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('num_simulations', models.IntegerField(default=1000, help_text='Number of simulation runs (typically 1000-10000)')),
                ('strategy_params', models.JSONField(default=dict, help_text='Base strategy parameters')),
                ('randomization_config', models.JSONField(default=dict, help_text="Randomization ranges for each parameter (e.g., {'rsi_oversold': {'min': 25, 'max': 35}})")),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('position_size', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=15)),
                ('mean_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average ROI across all simulations', max_digits=10)),
                ('median_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Median ROI', max_digits=10)),
                ('std_deviation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard deviation of returns', max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Variance of returns', max_digits=10)),
                ('confidence_95_lower', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('confidence_95_upper', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('confidence_99_lower', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('confidence_99_upper', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('probability_of_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of simulations with positive ROI', max_digits=5)),
                ('probability_of_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of simulations with negative ROI', max_digits=5)),
                ('value_at_risk_95', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VaR at 95% confidence', max_digits=10)),
                ('value_at_risk_99', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VaR at 99% confidence', max_digits=10)),
                ('mean_max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('worst_case_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('best_case_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('best_case_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('worst_case_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mean_sharpe_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('median_sharpe_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('mean_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('median_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('completed_simulations', models.IntegerField(default=0)),
                ('failed_simulations', models.IntegerField(default=0)),
                ('is_statistically_robust', models.BooleanField(default=False)),
                ('robustness_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0-100 robustness score', max_digits=5)),
                ('robustness_reasons', models.TextField(blank=True, help_text='Explanation of robustness assessment')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montecarlo_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'montecarlo_simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonteCarloRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField(help_text='Simulation run number (1 to N)')),
                ('parameters_used', models.JSONField(default=dict, help_text='The randomized parameters for this run')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_drawdown_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='signals.montecarlosimulation')),
            ],
            options={
                'db_table': 'montecarlo_runs',
                'ordering': ['run_number'],
            },
        ),
        migrations.CreateModel(
            name='MonteCarloDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('ROI', 'ROI Distribution'), ('DRAWDOWN', 'Max Drawdown Distribution'), ('WIN_RATE', 'Win Rate Distribution'), ('SHARPE', 'Sharpe Ratio Distribution'), ('PROFIT_FACTOR', 'Profit Factor Distribution'), ('TOTAL_TRADES', 'Total Trades Distribution')], max_length=20)),
                ('bins', models.JSONField(default=list, help_text='List of bin edges')),
                ('frequencies', models.JSONField(default=list, help_text='List of frequencies for each bin')),
                ('mean', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('median', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('std_dev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentile_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentile_25', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentile_75', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('percentile_95', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='signals.montecarlosimulation')),
            ],
            options={
                'db_table': 'montecarlo_distributions',
            },
        ),
        migrations.AddIndex(
            model_name='montecarlosimulation',
            index=models.Index(fields=['user', 'status'], name='montecarlo__user_id_93b4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='montecarlosimulation',
            index=models.Index(fields=['status', 'created_at'], name='montecarlo__status_078ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='montecarlosimulation',
            index=models.Index(fields=['completed_at'], name='montecarlo__complet_906144_idx'),
        ),
        migrations.AddIndex(
            model_name='montecarlorun',
            index=models.Index(fields=['simulation', 'run_number'], name='montecarlo__simulat_8e91ca_idx'),
        ),
        migrations.AddIndex(
            model_name='montecarlorun',
            index=models.Index(fields=['simulation', 'roi'], name='montecarlo__simulat_c338b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='montecarlorun',
            unique_together={('simulation', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='montecarlodistribution',
            index=models.Index(fields=['simulation', 'metric'], name='montecarlo__simulat_7fa9c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='montecarlodistribution',
            unique_together={('simulation', 'metric')},
        ),
    ]
