# Generated by Django 4.2.10 on 2025-10-30 06:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0010_montecarlosimulation_montecarlorun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTuningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('symbols', models.JSONField(default=list, help_text='List of trading symbols')),
                ('timeframe', models.CharField(default='5m', max_length=10)),
                ('training_start_date', models.DateTimeField()),
                ('training_end_date', models.DateTimeField()),
                ('validation_start_date', models.DateTimeField(blank=True, help_text='Optional validation period', null=True)),
                ('validation_end_date', models.DateTimeField(blank=True, null=True)),
                ('ml_algorithm', models.CharField(choices=[('RANDOM_FOREST', 'Random Forest'), ('GRADIENT_BOOSTING', 'Gradient Boosting (XGBoost)'), ('BAYESIAN_OPTIMIZATION', 'Bayesian Optimization'), ('NEURAL_NETWORK', 'Neural Network'), ('SVR', 'Support Vector Regression'), ('ENSEMBLE', 'Ensemble (Multiple Models)')], default='GRADIENT_BOOSTING', max_length=30)),
                ('optimization_metric', models.CharField(choices=[('ROI', 'Return on Investment'), ('SHARPE_RATIO', 'Sharpe Ratio'), ('PROFIT_FACTOR', 'Profit Factor'), ('WIN_RATE', 'Win Rate'), ('RISK_ADJUSTED_RETURN', 'Risk-Adjusted Return'), ('CUSTOM', 'Custom Metric')], default='SHARPE_RATIO', max_length=30)),
                ('parameter_space', models.JSONField(default=dict, help_text="Parameter ranges to explore (e.g., {'rsi_oversold': {'min': 20, 'max': 40}})")),
                ('ml_hyperparameters', models.JSONField(default=dict, help_text="ML model hyperparameters (e.g., {'n_estimators': 100, 'max_depth': 10})")),
                ('use_technical_indicators', models.BooleanField(default=True, help_text='Include technical indicators as features')),
                ('use_market_conditions', models.BooleanField(default=True, help_text='Include market conditions (volatility, trend)')),
                ('use_temporal_features', models.BooleanField(default=True, help_text='Include time-based features (hour, day)')),
                ('custom_features', models.JSONField(default=list, help_text='Custom feature definitions')),
                ('num_training_samples', models.IntegerField(default=1000, help_text='Number of parameter combinations to try')),
                ('train_test_split', models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='Train/test split ratio', max_digits=3)),
                ('cross_validation_folds', models.IntegerField(default=5, help_text='Number of CV folds')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('position_size', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=15)),
                ('best_parameters', models.JSONField(default=dict, help_text='Optimal parameters found by ML')),
                ('predicted_performance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="ML model's predicted performance", max_digits=10)),
                ('training_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='R² score on training set', max_digits=10)),
                ('validation_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='R² score on validation set', max_digits=10)),
                ('test_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='R² score on test set', max_digits=10)),
                ('out_of_sample_roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual ROI on validation period', max_digits=10)),
                ('out_of_sample_sharpe', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('out_of_sample_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('out_of_sample_max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores from ML model')),
                ('parameter_sensitivity', models.JSONField(default=dict, help_text='How sensitive performance is to each parameter')),
                ('model_file_path', models.CharField(blank=True, help_text='Path to saved model file', max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, help_text='Path to saved scaler file', max_length=500)),
                ('samples_evaluated', models.IntegerField(default=0)),
                ('samples_successful', models.IntegerField(default=0)),
                ('samples_failed', models.IntegerField(default=0)),
                ('overfitting_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between training and validation performance', max_digits=5)),
                ('model_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Model's confidence in predictions (0-100)", max_digits=5)),
                ('is_production_ready', models.BooleanField(default=False, help_text='Passes quality checks for production use')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_tuning_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_tuning_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, help_text='Parameters for which prediction was made')),
                ('features', models.JSONField(default=dict, help_text='Feature values used for prediction')),
                ('predicted_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text="ML model's predicted performance", max_digits=10)),
                ('prediction_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Model's confidence in this prediction", max_digits=5)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, help_text='Actual performance observed', max_digits=10, null=True)),
                ('prediction_error', models.DecimalField(blank=True, decimal_places=4, help_text='Difference between predicted and actual', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When actual value was verified', null=True)),
                ('tuning_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='signals.mltuningjob')),
            ],
            options={
                'db_table': 'ml_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ml_algorithm', models.CharField(max_length=30)),
                ('optimization_metric', models.CharField(max_length=30)),
                ('feature_set', models.JSONField(default=list, help_text='List of features used')),
                ('training_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('validation_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('test_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('model_file_path', models.CharField(max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, max_length=500)),
                ('metadata_file_path', models.CharField(blank=True, max_length=500)),
                ('times_used', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_production_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuning_job', models.ForeignKey(blank=True, help_text='Original tuning job that created this model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.mltuningjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLTuningSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(help_text='Sample number (1 to N)')),
                ('parameters', models.JSONField(default=dict, help_text='Parameters tested in this sample')),
                ('features', models.JSONField(default=dict, help_text='Feature values for this sample')),
                ('roi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_trades', models.IntegerField(default=0)),
                ('target_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='The optimization metric value (what ML predicts)', max_digits=10)),
                ('split_set', models.CharField(choices=[('TRAIN', 'Training'), ('TEST', 'Testing'), ('VALIDATION', 'Validation')], default='TRAIN', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tuning_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='signals.mltuningjob')),
            ],
            options={
                'db_table': 'ml_tuning_samples',
                'ordering': ['sample_number'],
                'indexes': [models.Index(fields=['tuning_job', 'sample_number'], name='ml_tuning_s_tuning__1ef0d1_idx'), models.Index(fields=['tuning_job', 'split_set'], name='ml_tuning_s_tuning__6e0f45_idx'), models.Index(fields=['tuning_job', 'target_value'], name='ml_tuning_s_tuning__560c82_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mltuningjob',
            index=models.Index(fields=['user', 'status'], name='ml_tuning_j_user_id_d09091_idx'),
        ),
        migrations.AddIndex(
            model_name='mltuningjob',
            index=models.Index(fields=['status', 'created_at'], name='ml_tuning_j_status_c7fcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='mltuningjob',
            index=models.Index(fields=['ml_algorithm'], name='ml_tuning_j_ml_algo_e64702_idx'),
        ),
        migrations.AddIndex(
            model_name='mltuningjob',
            index=models.Index(fields=['is_production_ready'], name='ml_tuning_j_is_prod_5d1557_idx'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['tuning_job', 'created_at'], name='ml_predicti_tuning__22b348_idx'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['tuning_job', 'predicted_value'], name='ml_predicti_tuning__fb16af_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['user', 'is_active'], name='ml_models_user_id_b75173_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['ml_algorithm'], name='ml_models_ml_algo_fd34e5_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['is_production_ready'], name='ml_models_is_prod_fd244e_idx'),
        ),
    ]
