# Generated by Django 4.2.10 on 2025-10-30 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0011_mltuningjob_mlprediction_mlmodel_mltuningsample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volatility_level', models.CharField(max_length=10, unique=True)),
                ('trade_count', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=200, help_text='Trigger optimization after N trades')),
                ('last_optimization', models.DateTimeField(blank=True, null=True)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trade Counter',
                'verbose_name_plural': 'Trade Counters',
                'db_table': 'trade_counter',
            },
        ),
        migrations.CreateModel(
            name='StrategyConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(help_text='Configuration name/version', max_length=100)),
                ('volatility_level', models.CharField(choices=[('HIGH', 'High Volatility'), ('MEDIUM', 'Medium Volatility'), ('LOW', 'Low Volatility'), ('ALL', 'All Volatility Levels')], default='ALL', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('parameters', models.JSONField(help_text='Strategy parameters (RSI, ADX, SL/TP multipliers, etc.)')),
                ('metrics', models.JSONField(blank=True, help_text='Performance metrics (win_rate, profit_factor, sharpe_ratio, etc.)', null=True)),
                ('improved', models.BooleanField(default=False, help_text='Whether this config improved over previous baseline')),
                ('improvement_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage improvement over baseline', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('TESTING', 'Testing'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], default='TESTING', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When this config was applied to live/paper trading', null=True)),
                ('trades_evaluated', models.IntegerField(default=0, help_text='Number of trades used to evaluate this config')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optimization notes or comments')),
                ('backtest_run', models.ForeignKey(blank=True, help_text='Backtest run used to evaluate this config', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_versions', to='signals.backtestrun')),
                ('baseline_config', models.ForeignKey(blank=True, help_text='Previous config this was compared against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvements', to='signals.strategyconfighistory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy Config History',
                'verbose_name_plural': 'Strategy Config Histories',
                'db_table': 'strategy_config_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='Unique run identifier', max_length=50, unique=True)),
                ('trigger', models.CharField(choices=[('TRADE_COUNT', 'Trade Count Threshold'), ('SCHEDULED', 'Scheduled Run'), ('MANUAL', 'Manual Trigger'), ('PERFORMANCE_DROP', 'Performance Drop Detected')], max_length=20)),
                ('volatility_level', models.CharField(default='ALL', max_length=10)),
                ('candidates_tested', models.IntegerField(default=0)),
                ('improvement_found', models.BooleanField(default=False)),
                ('baseline_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('best_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('improvement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('trades_analyzed', models.IntegerField(default=0)),
                ('lookback_days', models.IntegerField(default=30)),
                ('results', models.JSONField(blank=True, help_text='Detailed results including all candidate scores', null=True)),
                ('logs', models.TextField(blank=True, help_text='Execution logs')),
                ('error_message', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_config', models.ForeignKey(blank=True, help_text='Config being compared against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_for_runs', to='signals.strategyconfighistory')),
                ('winning_config', models.ForeignKey(blank=True, help_text='Best performing config from this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_runs', to='signals.strategyconfighistory')),
            ],
            options={
                'verbose_name': 'Optimization Run',
                'verbose_name_plural': 'Optimization Runs',
                'db_table': 'optimization_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='strategyconfighistory',
            index=models.Index(fields=['-created_at'], name='strategy_co_created_7a75e1_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyconfighistory',
            index=models.Index(fields=['volatility_level', '-created_at'], name='strategy_co_volatil_0690da_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyconfighistory',
            index=models.Index(fields=['status', '-created_at'], name='strategy_co_status_58c016_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyconfighistory',
            index=models.Index(fields=['improved', '-created_at'], name='strategy_co_improve_3a94d0_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrun',
            index=models.Index(fields=['-started_at'], name='optimizatio_started_7f5347_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrun',
            index=models.Index(fields=['status', '-started_at'], name='optimizatio_status_d4f304_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationrun',
            index=models.Index(fields=['improvement_found', '-started_at'], name='optimizatio_improve_d2a766_idx'),
        ),
    ]
