# Generated by Django 4.2.10 on 2025-11-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_tradecounter_strategyconfighistory_optimizationrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='market_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures'), ('FOREX', 'Forex')], default='SPOT', help_text='Market type (SPOT/FUTURES)', max_length=10),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='market_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures'), ('FOREX', 'Forex')], default='SPOT', help_text='Market type (SPOT/FUTURES)', max_length=10),
        ),
    ]
