# Generated by Django 4.2.10 on 2025-11-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_add_forex_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='signal',
            field=models.ForeignKey(blank=True, help_text='Associated trading signal (nullable to preserve trades)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_trades', to='signals.signal'),
        ),
    ]
