# Generated by Django 4.2.10 on 2025-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0017_signal_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='market_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], default='SPOT', help_text='Market type (SPOT/FUTURES)', max_length=10),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='market_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], default='SPOT', help_text='Market type (SPOT/FUTURES)', max_length=10),
        ),
    ]
