# Generated by Django 4.2.10 on 2025-12-11 15:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0018_alter_signal_market_type_alter_symbol_market_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesTradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable/disable futures trading')),
                ('trade_amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Base trade amount in USDT (before leverage)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('leverage', models.IntegerField(default=10, help_text='Leverage multiplier (1-125x)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)])),
                ('max_concurrent_trades', models.IntegerField(default=1, help_text='Maximum number of concurrent open trades', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_signal_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Minimum signal confidence to take trade', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('0.99'))])),
                ('allowed_symbols', models.JSONField(blank=True, default=list, help_text='List of allowed symbols for trading (empty = all)')),
                ('trade_long', models.BooleanField(default=True, help_text='Allow LONG trades')),
                ('trade_short', models.BooleanField(default=True, help_text='Allow SHORT trades')),
                ('use_trading_window', models.BooleanField(default=True, help_text='Only trade during trading windows (NPT 17:00-18:00 & 21:00-23:00)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Futures Trading Settings',
                'verbose_name_plural': 'Futures Trading Settings',
                'db_table': 'futures_trading_settings',
            },
        ),
        migrations.AlterField(
            model_name='signal',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Signal generated during high win-rate hours (17:00-18:00 or 21:00-23:00 Nepal Time)'),
        ),
        migrations.CreateModel(
            name='FuturesTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading pair symbol', max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], help_text='Trade direction', max_length=10)),
                ('leverage', models.IntegerField(help_text='Leverage used for this trade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)])),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Position quantity', max_digits=20)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, help_text='Entry price', max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=8, help_text='Stop loss price', max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, help_text='Take profit price', max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, help_text='Exit price', max_digits=20, null=True)),
                ('position_size_usdt', models.DecimalField(decimal_places=2, help_text='Position size in USDT (margin)', max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Realized P/L in USDT', max_digits=12)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='P/L percentage', max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED_TP', 'Closed - Take Profit'), ('CLOSED_SL', 'Closed - Stop Loss'), ('CLOSED_MANUAL', 'Closed - Manual'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Trade status', max_length=20)),
                ('binance_order_id', models.CharField(blank=True, help_text='Binance order ID for entry', max_length=100, null=True)),
                ('binance_exit_order_id', models.CharField(blank=True, help_text='Binance order ID for exit', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if trade failed')),
                ('entry_time', models.DateTimeField(blank=True, help_text='Time when position was opened', null=True)),
                ('exit_time', models.DateTimeField(blank=True, help_text='Time when position was closed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(blank=True, help_text='Associated trading signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='futures_trades', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Futures Trade',
                'verbose_name_plural': 'Futures Trades',
                'db_table': 'futures_trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='futures_tra_symbol_f5bb39_idx'), models.Index(fields=['status', '-created_at'], name='futures_tra_status_553b19_idx'), models.Index(fields=['signal', 'status'], name='futures_tra_signal__1ac1a0_idx')],
            },
        ),
    ]
