# Generated by Django 4.2.7 on 2024-12-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0019_futures_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Whether this is a Golden Window trade'),
        ),
    ]
