# Generated by Django 4.2.10 on 2025-12-13 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0022_futurestradingsettings_trade_on_golden_window_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibonacciSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('swing_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('swing_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('direction', models.CharField(choices=[('UP', 'Uptrend'), ('DOWN', 'Downtrend')], default='UP', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('annotation_type', models.CharField(choices=[('FIB', 'Fibonacci Level'), ('SUPPORT', 'Support Line'), ('RESISTANCE', 'Resistance Line'), ('TRENDLINE', 'Trendline'), ('NOTE', 'Note')], default='FIB', max_length=20)),
                ('price_level', models.DecimalField(decimal_places=8, max_digits=20)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', 'price_level'],
                'indexes': [models.Index(fields=['symbol', 'is_active'], name='signals_cha_symbol_19ef91_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Symbol to blacklist (e.g., BTCUSDT)', max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('HIGH_VOLATILITY', 'High Volatility - Too risky'), ('LOW_LIQUIDITY', 'Low Liquidity - Poor fills'), ('POOR_PERFORMANCE', 'Poor Performance - Consistent losses'), ('DELISTED', 'Delisted - No longer available'), ('TEMPORARY', 'Temporary - Short-term exclusion'), ('MANUAL', 'Manual - User preference'), ('OTHER', 'Other')], default='MANUAL', help_text='Reason for blacklisting', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about why this symbol is blacklisted', null=True)),
                ('blacklisted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this symbol was blacklisted')),
                ('blacklisted_until', models.DateTimeField(blank=True, help_text='Auto-remove from blacklist after this date (optional)', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this blacklist entry is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Symbol',
                'verbose_name_plural': 'Blacklisted Symbols',
                'db_table': 'signals_blacklisted_symbols',
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['symbol', 'active'], name='signals_bla_symbol_7d1127_idx'), models.Index(fields=['active', 'blacklisted_at'], name='signals_bla_active_be5843_idx')],
            },
        ),
    ]
