# Generated by Django 4.2.10 on 2025-12-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0024_remove_mlmodel_tuning_job_remove_mlmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyoptimization',
            name='backtest_run',
        ),
        migrations.RemoveField(
            model_name='strategyoptimization',
            name='user',
        ),
        migrations.DeleteModel(
            name='OptimizationRecommendation',
        ),
        migrations.DeleteModel(
            name='StrategyOptimization',
        ),
    ]
