# Generated by Django 4.2.10 on 2025-12-19 18:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0024_tradingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestradingsettings',
            name='gw_auto_trader_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic trading during golden windows (GW1/GW2)'),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='max_active_gw_trades',
            field=models.IntegerField(default=4, help_text='Maximum trades to execute during a golden window session (capital divided equally)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='total_trading_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Total capital to divide equally among max_active_gw_trades', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
    ]
