# Generated by Django 4.2.10 on 2025-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0026_futurestrade_live_pnl_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='is_golden_2',
            field=models.BooleanField(default=False, help_text='Signal generated during premium windows (16:00-17:00 or 21:00-23:00 NPT) on Sun/Wed/Thu only'),
        ),
    ]
