# Generated by Django 4.2.10 on 2025-12-22 07:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0027_add_is_golden_2_to_signal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradingsession',
            new_name='trading_ses_active_190f4b_idx',
            old_name='trading_ses_active_c7c2e5_idx',
        ),
        migrations.RenameIndex(
            model_name='tradingsession',
            new_name='trading_ses_start_h_16cfe0_idx',
            old_name='trading_ses_start_h_e36f43_idx',
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='current_trailing_tier',
            field=models.IntegerField(default=0, help_text='Current dynamic trailing tier level (0 = base tier)'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='cut_loser_triggered',
            field=models.BooleanField(default=False, help_text='Whether cut-loser mode has been triggered for this trade'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='max_loss_pct_reached',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Maximum loss percentage reached during trade', max_digits=8),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='max_profit_pct_reached',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Maximum profit percentage reached during trade', max_digits=8),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='trailing_order_id',
            field=models.CharField(blank=True, help_text='Current trailing stop order ID on Binance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='cut_loser_close_at_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.3'), help_text='Close trade when it recovers to this % from entry (-1% to +1%, negative = small loss, positive = small profit)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-1.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))]),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='cut_loser_enabled',
            field=models.BooleanField(default=False, help_text="Enable 'cut loser first' - close losing trades when they recover near breakeven"),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='cut_loser_trigger_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Trigger cut-loser when unrealized loss exceeds this % (0.5% - 10%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='dynamic_trailing_enabled',
            field=models.BooleanField(default=False, help_text='Enable dynamic trailing stop that tightens as profit grows'),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='dynamic_trailing_tiers',
            field=models.JSONField(blank=True, default=list, help_text='List of profit tiers: [{profit_pct: 2, trailing_pct: 1}, {profit_pct: 3, trailing_pct: 2}]'),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='initial_trailing_callback',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Initial trailing stop callback % before any tier is reached (0.1% - 5.0%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='use_trading_window',
            field=models.BooleanField(default=True, help_text='Only trade during trading windows (NPT 16:00-17:00 & 21:00-23:00)'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Signal generated during high win-rate hours (16:00-17:00 or 21:00-23:00 Nepal Time)'),
        ),
    ]
