# Generated by Django 4.2.10 on 2026-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0028_rename_trading_ses_active_c7c2e5_idx_trading_ses_active_190f4b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paperaccount',
            index=models.Index(fields=['auto_trading_enabled'], name='paper_acct_auto_trade_idx'),
        ),
        migrations.AddIndex(
            model_name='paperaccount',
            index=models.Index(fields=['-total_pnl'], name='paper_acct_pnl_idx'),
        ),
        migrations.AddIndex(
            model_name='paperaccount',
            index=models.Index(fields=['-updated_at'], name='paper_acct_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='paperaccount',
            index=models.Index(fields=['-win_rate'], name='paper_acct_winrate_idx'),
        ),
    ]
