# Generated by Django 4.2.10 on 2026-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0029_add_paper_account_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['is_priority', 'status'], name='paper_trade_gw1_status_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['is_golden_2', 'status'], name='paper_trade_gw2_status_idx'),
        ),
    ]
