# Generated by Django 4.2.10 on 2026-03-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0030_add_golden_window_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrade',
            name='sl_order_id',
            field=models.CharField(blank=True, help_text='Binance order/algo ID for stop loss', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='tp_order_id',
            field=models.CharField(blank=True, help_text='Binance order/algo ID for take profit', max_length=100, null=True),
        ),
    ]
