# Generated by Django 4.2.10 on 2026-03-16 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0031_add_sl_tp_order_ids_to_futures_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestradingsettings',
            name='fear_greed_enabled',
            field=models.BooleanField(default=False, help_text='Enable Fear & Greed Index filter for trade direction'),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='fear_greed_long_threshold',
            field=models.IntegerField(default=60, help_text='F&G >= this: only LONG allowed (Greed). Range: 50-95', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(95)]),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='fear_greed_short_threshold',
            field=models.IntegerField(default=30, help_text='F&G <= this: only SHORT allowed (Extreme Fear). Range: 5-50', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
