# Generated by Django 4.2.10 on 2026-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0032_add_fear_greed_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsession',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Whether this session was auto-generated by the optimizer'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='last_optimized_at',
            field=models.DateTimeField(blank=True, help_text='When this window was last updated by the optimizer', null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='total_trades_analyzed',
            field=models.IntegerField(default=0, help_text='Number of trades analyzed when this window was generated'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Win rate % when this window was last analyzed', max_digits=5, null=True),
        ),
    ]
