# Generated by Django 4.2.10 on 2026-03-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0033_add_trading_session_auto_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesTradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SIGNAL_RECEIVED', 'Signal Received'), ('CHECK_PASSED', 'Check Passed'), ('CHECK_FAILED', 'Check Failed'), ('TRADE_SUBMITTED', 'Trade Submitted'), ('TRADE_EXECUTED', 'Trade Executed'), ('TRADE_FAILED', 'Trade Failed'), ('TRADE_CLOSED', 'Trade Closed'), ('ORDER_PLACED', 'Order Placed'), ('ORDER_FAILED', 'Order Failed')], max_length=30)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('is_priority', models.BooleanField(default=False)),
                ('force_execute', models.BooleanField(default=False)),
                ('message', models.TextField(help_text='Human-readable log message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra details (settings, prices, errors, order IDs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='futures_logs', to='signals.signal')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='signals.futurestrade')),
            ],
            options={
                'verbose_name': 'Futures Trade Log',
                'verbose_name_plural': 'Futures Trade Logs',
                'db_table': 'futures_trade_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='futures_tra_created_4ff600_idx'), models.Index(fields=['signal', '-created_at'], name='futures_tra_signal__690ce0_idx'), models.Index(fields=['action', '-created_at'], name='futures_tra_action_83feda_idx'), models.Index(fields=['level', '-created_at'], name='futures_tra_level_d79daa_idx'), models.Index(fields=['symbol', '-created_at'], name='futures_tra_symbol_a423f8_idx')],
            },
        ),
    ]
