# Generated by Django 4.2.10 on 2026-03-20 06:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0034_futures_trade_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestradingsettings',
            name='neutral_reversal_enabled',
            field=models.BooleanField(default=False, help_text='In neutral F&G zone, reverse signal direction and use tight SL/TP'),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='neutral_reversal_sl_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Stop loss % for neutral market reversed trades (default 1.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AddField(
            model_name='futurestradingsettings',
            name='neutral_reversal_tp_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.5'), help_text='Take profit % for neutral market reversed trades (default 2.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
