# Generated by Django 4.2.10 on 2026-03-20 07:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0035_neutral_reversal_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], help_text='Timeframe this config applies to', max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timeframe is actively scanned')),
                ('min_confidence', models.FloatField(default=0.7, help_text='Minimum confidence score to generate signal (0.5-1.0)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)])),
                ('long_rsi_min', models.FloatField(default=23.0, help_text='RSI minimum for LONG entry (oversold zone)', validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(50.0)])),
                ('long_rsi_max', models.FloatField(default=33.0, help_text='RSI maximum for LONG entry', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(60.0)])),
                ('short_rsi_min', models.FloatField(default=67.0, help_text='RSI minimum for SHORT entry', validators=[django.core.validators.MinValueValidator(40.0), django.core.validators.MaxValueValidator(90.0)])),
                ('short_rsi_max', models.FloatField(default=77.0, help_text='RSI maximum for SHORT entry (overbought zone)', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(95.0)])),
                ('long_adx_min', models.FloatField(default=26.0, help_text='Minimum ADX for LONG trend strength', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(50.0)])),
                ('short_adx_min', models.FloatField(default=26.0, help_text='Minimum ADX for SHORT trend strength', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(50.0)])),
                ('long_volume_multiplier', models.FloatField(default=1.2, help_text='Volume must be this multiple of average for LONG', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('short_volume_multiplier', models.FloatField(default=1.2, help_text='Volume must be this multiple of average for SHORT', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('sl_atr_multiplier', models.FloatField(default=3.0, help_text='Stop loss as ATR multiplier (for backtest engine)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)])),
                ('tp_atr_multiplier', models.FloatField(default=9.0, help_text='Take profit as ATR multiplier (for backtest engine)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(20.0)])),
                ('sl_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Stop loss as percentage from entry price (for live signals)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('tp_percentage', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Take profit as percentage from entry price (for live signals)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('risk_reward_ratio', models.FloatField(default=3.0, help_text='Target risk/reward ratio', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)])),
                ('macd_weight', models.FloatField(default=2.0, help_text='MACD signal weight')),
                ('rsi_weight', models.FloatField(default=1.5, help_text='RSI signal weight')),
                ('price_ema_weight', models.FloatField(default=1.8, help_text='Price vs EMA weight')),
                ('adx_weight', models.FloatField(default=1.7, help_text='ADX trend strength weight')),
                ('ha_weight', models.FloatField(default=1.6, help_text='Heikin-Ashi trend weight')),
                ('volume_weight', models.FloatField(default=1.4, help_text='Volume confirmation weight')),
                ('ema_alignment_weight', models.FloatField(default=1.2, help_text='EMA alignment weight')),
                ('di_weight', models.FloatField(default=1.0, help_text='Directional indicator weight')),
                ('bb_weight', models.FloatField(default=0.8, help_text='Bollinger Bands weight')),
                ('volatility_weight', models.FloatField(default=0.5, help_text='Volatility adjustment weight')),
                ('supertrend_weight', models.FloatField(default=1.9, help_text='SuperTrend weight')),
                ('mfi_weight', models.FloatField(default=1.3, help_text='Money Flow Index weight')),
                ('psar_weight', models.FloatField(default=1.1, help_text='Parabolic SAR weight')),
                ('fibonacci_weight', models.FloatField(default=2.5, help_text='Fibonacci pullback weight')),
                ('fib_lookback_candles', models.IntegerField(default=50, help_text='Candles to search for Fibonacci swing points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)])),
                ('fib_entry_zone_min', models.FloatField(default=0.5, help_text='Fibonacci entry zone minimum (0.5 = 50% retracement)')),
                ('fib_entry_zone_max', models.FloatField(default=0.618, help_text='Fibonacci entry zone maximum (0.618 = golden ratio)')),
                ('fib_enable_pullback', models.BooleanField(default=True, help_text='Enable Fibonacci pullback detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategy Config',
                'verbose_name_plural': 'Strategy Configs',
                'db_table': 'strategy_configs',
                'ordering': ['timeframe'],
            },
        ),
    ]
