# Generated by Django 4.2.10 on 2026-03-20 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0036_strategy_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='adx_period',
            field=models.IntegerField(default=14, help_text='ADX calculation period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='atr_period',
            field=models.IntegerField(default=14, help_text='ATR calculation period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='bb_period',
            field=models.IntegerField(default=20, help_text='Bollinger Bands period', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='bb_std_dev',
            field=models.FloatField(default=2.0, help_text='Bollinger Bands standard deviation', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='ema_fast',
            field=models.IntegerField(default=9, help_text='Fast EMA period', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='ema_medium',
            field=models.IntegerField(default=21, help_text='Medium EMA period', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='ema_slow',
            field=models.IntegerField(default=50, help_text='Slow EMA period', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='ema_trend',
            field=models.IntegerField(default=200, help_text='Trend EMA period (long-term)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='macd_fast',
            field=models.IntegerField(default=12, help_text='MACD fast EMA period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='macd_signal',
            field=models.IntegerField(default=9, help_text='MACD signal line period', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='macd_slow',
            field=models.IntegerField(default=26, help_text='MACD slow EMA period', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='mfi_period',
            field=models.IntegerField(default=14, help_text='Money Flow Index period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='psar_acceleration',
            field=models.FloatField(default=0.02, help_text='Parabolic SAR acceleration factor', validators=[django.core.validators.MinValueValidator(0.005), django.core.validators.MaxValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='psar_maximum',
            field=models.FloatField(default=0.2, help_text='Parabolic SAR maximum acceleration', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='rsi_period',
            field=models.IntegerField(default=14, help_text='RSI calculation period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='supertrend_multiplier',
            field=models.FloatField(default=3.0, help_text='SuperTrend ATR multiplier', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='supertrend_period',
            field=models.IntegerField(default=10, help_text='SuperTrend ATR period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='volume_ma_period',
            field=models.IntegerField(default=20, help_text='Volume moving average period', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
