# Generated by Django 4.2.10 on 2026-03-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0038_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='progress_log',
            field=models.JSONField(blank=True, default=list, help_text='Step-by-step execution log'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='progress_pct',
            field=models.IntegerField(default=0, help_text='Progress percentage 0-100'),
        ),
    ]
