# Generated by Django 4.2.10 on 2026-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0039_backtest_progress_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='fear_greed_at_entry',
            field=models.IntegerField(blank=True, help_text='Fear & Greed Index value when trade was opened', null=True),
        ),
    ]
