# Generated by Django 4.2.10 on 2026-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0041_user_binance_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyconfig',
            name='timeframe',
            field=models.CharField(choices=[('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], help_text='Timeframe this config applies to', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='userbinanceconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
