# Generated by Django 4.2.10 on 2026-04-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0042_alter_strategyconfig_timeframe_and_more'),
        ('signals', '0042_futurestrade_user'),
    ]

    operations = [
    ]
