# Generated by Django 4.2.10 on 2026-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0043_asset_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyconfig',
            name='timeframe',
            field=models.CharField(choices=[('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], help_text='Timeframe this config applies to', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='avg_pnl_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Average profit_loss_percentage per trade', max_digits=10),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='best_trade_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Largest single-trade profit_loss_percentage in the period', max_digits=10),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this row was last (re)calculated'),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='period_end',
            field=models.DateField(help_text='Last day of the calendar month (inclusive)'),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='period_start',
            field=models.DateField(help_text='First day of the calendar month covered (YYYY-MM-01)'),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='rank',
            field=models.PositiveSmallIntegerField(help_text='1 = highest PnL in the period; 10 = lowest of the top 10'),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='symbol',
            field=models.CharField(help_text='Trading pair symbol, e.g. BTCUSDT', max_length=20),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='total_pnl',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Sum of profit_loss in USDT for all closed trades in the period', max_digits=14),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='total_pnl_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Sum of profit_loss_percentage values', max_digits=10),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Win percentage (0-100), 1 d.p.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='topperformingsymbol',
            name='worst_trade_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Largest single-trade loss percentage in the period (signed)', max_digits=10),
        ),
    ]
