# Generated by Django 4.2.10 on 2026-05-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0044_alter_strategyconfig_timeframe_and_more'),
        ('signals', '0044_per_class_macro_filter_flags'),
    ]

    operations = [
    ]
