# Generated by Django 4.2.10 on 2026-05-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0045_merge_20260515_0503'),
        ('signals', '0046_last_balance_updated_at'),
    ]

    operations = [
    ]
