# Generated by Django 4.2.10 on 2026-06-05 04:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0047_merge_20260515_0711'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chartannotation',
            name='signals_cha_symbol_19ef91_idx',
        ),
        migrations.RenameIndex(
            model_name='balancerebalancelog',
            new_name='balance_reb_created_797b5c_idx',
            old_name='balance_reb_created_8d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='balancerebalancelog',
            new_name='balance_reb_applied_38ba7d_idx',
            old_name='balance_reb_applied_5d4a1c_idx',
        ),
        migrations.AddField(
            model_name='chartannotation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fibonaccisetup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fibonacci_setups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balancerebalancelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fibonaccisetup',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='commodity_macro_filter_enabled',
            field=models.BooleanField(default=True, help_text="Enable XAU (gold) macro filter for COMMODITY signals (XAU, XAG, CL, ...). When ON, orders on tokenized-commodity perps are blocked if gold's daily regime contradicts the signal direction."),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='crypto_macro_filter_enabled',
            field=models.BooleanField(default=True, help_text="Enable BTC macro filter for CRYPTO signals at the Binance trade boundary. When ON, futures orders on crypto perps are blocked if BTC's daily regime contradicts the signal direction."),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='macro_filter_enabled',
            field=models.BooleanField(default=True, help_text='Legacy global toggle. Kept for backwards compatibility — the per-class flags (crypto/stock/commodity_macro_filter_enabled) are the source of truth used at the trade boundary. New deployments should ignore this field.'),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='stock_macro_filter_enabled',
            field=models.BooleanField(default=True, help_text="Enable SPY macro filter for STOCK signals (NVDA, MSTR, TSLA, ...). When ON, orders on tokenized-equity perps are blocked if SPY's daily regime contradicts the signal direction."),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='total_trading_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Last known Binance futures USDT wallet balance. Written by the monthly rebalance task (signals.monthly_balance_rebalance) and read by the frontend balance display. Also used by the Golden Window auto-trader as the per-trade sizing pool (per_trade = total_trading_capital / max_active_gw_trades).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='fibonaccisetup',
            unique_together={('user', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='chartannotation',
            index=models.Index(fields=['user', 'symbol', 'is_active'], name='signals_cha_user_id_ee51e4_idx'),
        ),
    ]
