# Generated by Django 4.2.10 on 2026-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0048_remove_chartannotation_signals_cha_symbol_19ef91_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['user', '-entry_time'], name='paper_trade_user_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['-entry_time'], name='paper_trade_entry_time_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['symbol', '-entry_time'], name='paper_trade_symbol_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['symbol', 'direction', 'timeframe', 'market_type', 'status', '-created_at'], name='signal_dedup_idx'),
        ),
    ]
