# Generated by Django 4.2.10 on 2026-06-13 08:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0049_papertrade_paper_trade_user_entry_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTradePaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Starting balance in USDT', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Available balance in USDT', max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Balance plus unrealized P/L', max_digits=12)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Win rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Default account risk per trade (percent)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('max_open_trades', models.IntegerField(default=5, help_text='Maximum concurrent open day-trades', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_trade_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Day-Trade Paper Account',
                'verbose_name_plural': 'Day-Trade Paper Accounts',
                'db_table': 'daytrade_paper_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayTradePaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading pair symbol', max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], help_text='Trade direction', max_length=10)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], default='FUTURES', help_text='Market type', max_length=10)),
                ('timeframe', models.CharField(default='15m', help_text='Entry timeframe', max_length=5)),
                ('confidence', models.FloatField(blank=True, help_text='Signal confidence at entry', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('entry_price', models.DecimalField(decimal_places=8, help_text='Average entry price', max_digits=20)),
                ('entry_time', models.DateTimeField(blank=True, help_text='Time the position was entered', null=True)),
                ('position_size', models.DecimalField(decimal_places=8, default=Decimal('100.00'), help_text='Position notional in USDT (from risk-based sizing)', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Total opened quantity of the asset', max_digits=20)),
                ('remaining_quantity', models.DecimalField(decimal_places=8, help_text='Quantity still open after partial exits', max_digits=20)),
                ('initial_stop_loss', models.DecimalField(decimal_places=8, help_text='Original 1.8 x ATR stop at entry', max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, help_text='Current effective stop loss', max_digits=20)),
                ('trailing_stop', models.DecimalField(blank=True, decimal_places=8, help_text='Trailing stop for the runner (Highest -/+ 2 x ATR)', max_digits=20, null=True)),
                ('tp1_price', models.DecimalField(decimal_places=8, help_text='TP1 target (2 x ATR)', max_digits=20)),
                ('tp2_price', models.DecimalField(decimal_places=8, help_text='TP2 target (4 x ATR)', max_digits=20)),
                ('atr_at_entry', models.DecimalField(decimal_places=8, help_text='ATR at entry, used for trailing-stop distance', max_digits=20)),
                ('tp1_filled', models.BooleanField(default=False, help_text='TP1 leg closed')),
                ('tp2_filled', models.BooleanField(default=False, help_text='TP2 leg closed')),
                ('account_risk_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Account risk percent used for position sizing', max_digits=5)),
                ('stop_distance', models.DecimalField(blank=True, decimal_places=8, help_text='Entry-to-stop distance used for position sizing', max_digits=20, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, help_text='Final/average exit price once fully closed', max_digits=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, help_text='Time the position was fully closed', null=True)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, help_text='Realized P/L accumulated across partial exits (USDT)', max_digits=20)),
                ('profit_loss', models.DecimalField(decimal_places=8, default=0, help_text='Total realized P/L for the trade (USDT)', max_digits=20)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, default=0, help_text='Total P/L as percent of notional', max_digits=10)),
                ('leverage', models.IntegerField(blank=True, help_text='Leverage for futures', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Entry'), ('OPEN', 'Open'), ('PARTIAL', 'Partially Closed'), ('CLOSED_TP', 'Closed - Take Profit'), ('CLOSED_SL', 'Closed - Stop Loss'), ('CLOSED_TRAIL', 'Closed - Trailing Stop'), ('CLOSED_MANUAL', 'Closed - Manually'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current trade status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day-Trade Paper Trade',
                'verbose_name_plural': 'Day-Trade Paper Trades',
                'db_table': 'daytrade_paper_trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayTradeTradeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('TP1', 'Take Profit 1'), ('TP2', 'Take Profit 2'), ('TRAIL', 'Trailing Stop'), ('SL', 'Stop Loss'), ('MANUAL', 'Manual')], help_text='Which leg of the exit plan this fill represents', max_length=10)),
                ('price', models.DecimalField(decimal_places=8, help_text='Fill price for this leg', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity closed in this leg', max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=8, default=0, help_text='Realized P/L for this leg (USDT)', max_digits=20)),
                ('exit_time', models.DateTimeField(help_text='Time this leg was closed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(help_text='Parent day-trade', on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='signals.daytradepapertrade')),
            ],
            options={
                'verbose_name': 'Day-Trade Trade Exit',
                'verbose_name_plural': 'Day-Trade Trade Exits',
                'db_table': 'daytrade_trade_exits',
                'ordering': ['exit_time'],
            },
        ),
        migrations.CreateModel(
            name='DayTradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair symbol', max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], help_text='Trade direction (LONG/SHORT)', max_length=10)),
                ('entry_timeframe', models.CharField(default='15m', help_text='Entry/execution timeframe', max_length=5)),
                ('trend_timeframe', models.CharField(default='1h', help_text='Higher timeframe used for the trend filter', max_length=5)),
                ('candle_open_time', models.DateTimeField(help_text='Open time of the entry-timeframe candle this signal belongs to')),
                ('entry', models.DecimalField(decimal_places=8, help_text='Entry price', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('stop_loss', models.DecimalField(decimal_places=8, help_text='Initial stop loss price (Entry -/+ 1.8 x ATR)', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('tp1', models.DecimalField(decimal_places=8, help_text='Take profit 1 price (2 x ATR)', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('tp2', models.DecimalField(decimal_places=8, help_text='Take profit 2 price (4 x ATR)', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('atr', models.DecimalField(decimal_places=8, help_text='ATR value at signal time, used for trailing-stop sizing', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence', models.FloatField(default=0.0, help_text='Normalized confidence (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('score', models.FloatField(default=0.0, help_text='Raw weighted score (max 13.5)')),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], default='FUTURES', help_text='Market type', max_length=10)),
                ('leverage', models.IntegerField(blank=True, help_text='Leverage for futures', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', help_text='Signal status', max_length=10)),
                ('source', models.CharField(default='daytrade_engine', help_text='Signal source', max_length=100)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Structure, pullback zone, liquidity sweep and score breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signal expiration time', null=True)),
            ],
            options={
                'verbose_name': 'Day-Trade Signal',
                'verbose_name_plural': 'Day-Trade Signals',
                'db_table': 'daytrade_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'direction', '-created_at'], name='daytrade_si_symbol_bea072_idx'), models.Index(fields=['status', '-created_at'], name='daytrade_si_status_2fbf6e_idx'), models.Index(fields=['-confidence', '-created_at'], name='daytrade_si_confide_38a878_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='daytradesignal',
            constraint=models.UniqueConstraint(fields=('symbol', 'entry_timeframe', 'candle_open_time', 'direction'), name='daytrade_signal_dedup'),
        ),
        migrations.AddField(
            model_name='daytradepapertrade',
            name='signal',
            field=models.ForeignKey(blank=True, help_text='Originating day-trade signal (nullable to preserve trades)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_trades', to='signals.daytradesignal'),
        ),
        migrations.AddField(
            model_name='daytradepapertrade',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner (null for the system-wide bot)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daytrade_paper_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daytradepaperaccount',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Owner (null for the system-wide bot account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daytrade_paper_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='daytradetradeexit',
            index=models.Index(fields=['trade', 'exit_time'], name='daytrade_tr_trade_i_9520eb_idx'),
        ),
        migrations.AddIndex(
            model_name='daytradepapertrade',
            index=models.Index(fields=['status', '-created_at'], name='daytrade_pa_status_e785d6_idx'),
        ),
        migrations.AddIndex(
            model_name='daytradepapertrade',
            index=models.Index(fields=['symbol', 'status'], name='daytrade_pa_symbol_ae1660_idx'),
        ),
        migrations.AddIndex(
            model_name='daytradepapertrade',
            index=models.Index(fields=['user', 'status'], name='daytrade_pa_user_id_80cca7_idx'),
        ),
        migrations.AddIndex(
            model_name='daytradepapertrade',
            index=models.Index(fields=['-entry_time'], name='daytrade_pa_entry_t_a75ba6_idx'),
        ),
        migrations.AddConstraint(
            model_name='daytradepapertrade',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'OPEN', 'PARTIAL'])), fields=('symbol',), name='daytrade_one_open_per_symbol'),
        ),
        migrations.AddIndex(
            model_name='daytradepaperaccount',
            index=models.Index(fields=['-total_pnl'], name='daytrade_acct_pnl_idx'),
        ),
        migrations.AddIndex(
            model_name='daytradepaperaccount',
            index=models.Index(fields=['-updated_at'], name='daytrade_acct_updated_idx'),
        ),
    ]
