# Generated by Django 4.2.10 on 2026-06-13 09:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0050_daytradepaperaccount_daytradepapertrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTradeStrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Config name (one active config drives the engine)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this config is the one the engine uses')),
                ('symbols', models.JSONField(blank=True, default=list, help_text='Symbols to scan, e.g. ["BTCUSDT", "ETHUSDT"]')),
                ('entry_timeframe', models.CharField(default='15m', help_text='Entry/execution timeframe', max_length=5)),
                ('trend_timeframe', models.CharField(default='1h', help_text='Higher-timeframe trend filter', max_length=5)),
                ('trend_ema_fast', models.PositiveIntegerField(default=50, help_text='Fast EMA for the trend filter', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(400)])),
                ('trend_ema_slow', models.PositiveIntegerField(default=200, help_text='Slow EMA for the trend filter', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)])),
                ('pivot_lookback', models.PositiveIntegerField(default=5, help_text='Candles each side that define a confirmed swing point', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('pullback_ema_fast', models.PositiveIntegerField(default=20, help_text='Fast EMA of the pullback zone', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(200)])),
                ('pullback_ema_slow', models.PositiveIntegerField(default=50, help_text='Slow EMA of the pullback zone', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(400)])),
                ('use_vwap', models.BooleanField(default=True, help_text='Include VWAP in the pullback zone')),
                ('vwap_anchor', models.CharField(choices=[('daily_utc', 'Daily (00:00 UTC reset)'), ('rolling', 'Rolling N-period')], default='daily_utc', help_text='How VWAP is anchored', max_length=12)),
                ('rsi_period', models.PositiveIntegerField(default=14, help_text='RSI period', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('rsi_threshold', models.FloatField(default=50.0, help_text='RSI midline (LONG above, SHORT below)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(99.0)])),
                ('macd_fast', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('macd_slow', models.PositiveIntegerField(default=26, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(200)])),
                ('macd_signal', models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('volume_multiplier', models.FloatField(default=1.3, help_text='Volume must exceed this multiple of its average', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('volume_avg_period', models.PositiveIntegerField(default=20, help_text='Lookback for the average-volume baseline', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(200)])),
                ('adx_min', models.FloatField(default=20.0, help_text='Minimum ADX for a tradeable trend', validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(60.0)])),
                ('adx_period', models.PositiveIntegerField(default=14, help_text='ADX period', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('atr_period', models.PositiveIntegerField(default=14, help_text='ATR period for stops and targets', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('sl_atr_mult', models.FloatField(default=1.8, help_text='Initial stop = entry -/+ this x ATR', validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(10.0)])),
                ('tp1_atr_mult', models.FloatField(default=2.0, help_text='TP1 distance in ATR multiples', validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(20.0)])),
                ('tp1_close_pct', models.FloatField(default=50.0, help_text='Percent of position closed at TP1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('tp2_atr_mult', models.FloatField(default=4.0, help_text='TP2 distance in ATR multiples', validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(40.0)])),
                ('tp2_close_pct', models.FloatField(default=30.0, help_text='Percent of position closed at TP2', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('runner_pct', models.FloatField(default=20.0, help_text='Percent left as the trailing runner', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('trail_atr_mult', models.FloatField(default=2.0, help_text='Trailing-stop distance in ATR multiples', validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(20.0)])),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Account risk per trade (percent), for position sizing', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('enable_liquidity_sweep', models.BooleanField(default=True, help_text='Score the optional liquidity-sweep confirmation')),
                ('weight_trend', models.FloatField(default=3.0, help_text='1H trend filter weight')),
                ('weight_structure', models.FloatField(default=3.0, help_text='Market-structure weight')),
                ('weight_volume', models.FloatField(default=2.0, help_text='Volume confirmation weight')),
                ('weight_pullback', models.FloatField(default=2.0, help_text='Pullback-zone weight')),
                ('weight_macd', models.FloatField(default=1.5, help_text='MACD momentum weight')),
                ('weight_rsi', models.FloatField(default=1.0, help_text='RSI momentum weight')),
                ('weight_atr', models.FloatField(default=1.0, help_text='ATR regime weight')),
                ('min_score', models.FloatField(default=8.5, help_text='Minimum weighted score (of 13.5) to emit a signal', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(13.5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day-Trade Strategy Config',
                'verbose_name_plural': 'Day-Trade Strategy Configs',
                'db_table': 'daytrade_strategy_configs',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
