# Generated by Django 4.2.10 on 2026-06-13 10:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0051_daytradestrategyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='leverage',
            field=models.PositiveIntegerField(default=10, help_text='Leverage applied to each paper trade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)]),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='margin_per_trade',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Fixed margin (USDT) committed per paper trade', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='min_confidence',
            field=models.FloatField(default=0.7, help_text='Minimum confidence (0-1) to emit a signal and paper trade it', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='daytradestrategyconfig',
            name='risk_per_trade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Account risk per trade (percent) — unused while fixed margin sizing is on', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
    ]
