# Generated by Django 4.2.10 on 2026-06-13 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0052_daytradestrategyconfig_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='universe_top_n',
            field=models.PositiveIntegerField(default=30, help_text='When symbols is ["*"], scan only the top N pairs by 24h volume (0 = all)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='daytradestrategyconfig',
            name='symbols',
            field=models.JSONField(blank=True, default=list, help_text='Symbols to scan, e.g. ["BTCUSDT", "ETHUSDT"]. Use ["*"] for all.'),
        ),
    ]
