# Generated by Django 4.2.10 on 2026-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0055_futurestrade_entry_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='block_on_choch',
            field=models.BooleanField(default=False, help_text='Reject on Change of Character (validated: off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_atr_percentile_min',
            field=models.FloatField(default=30.0, help_text='Require ATR percentile (0-100) >= this (validated: 30)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_atr_percentile_period',
            field=models.PositiveIntegerField(default=100, help_text='Lookback bars for the ATR percentile'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_bb_period',
            field=models.PositiveIntegerField(default=20, help_text='Bollinger period for band width'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_bb_std',
            field=models.FloatField(default=2.0, help_text='Bollinger std-dev multiplier'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_choppiness_period',
            field=models.PositiveIntegerField(default=14, help_text='Choppiness Index lookback'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_filter_enabled',
            field=models.BooleanField(default=True, help_text='V3: market-regime gate before scanning (validated: on)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_max_choppiness',
            field=models.FloatField(default=0.0, help_text='Reject if Choppiness Index > this (validated: 0/off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_min_adx',
            field=models.FloatField(default=0.0, help_text='Require 15m ADX >= this (validated: 0/off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='regime_min_bbw_pct',
            field=models.FloatField(default=0.0, help_text='Min Bollinger band width %% (validated: 0/off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='require_bos',
            field=models.BooleanField(default=False, help_text='Require a Break of Structure (validated: off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='structure_min_swing_atr',
            field=models.FloatField(default=0.0, help_text='Ignore swing legs smaller than this x ATR (0 = off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='structure_quality_enabled',
            field=models.BooleanField(default=False, help_text='V3: use significance-filtered swings + structure bonus (validated: off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='trend_filter_enabled',
            field=models.BooleanField(default=True, help_text='V3: 1H trend-strength gate beyond the EMA cross (validated: on)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='trend_min_ema_gap_pct',
            field=models.FloatField(default=0.5, help_text='Min EMA50-EMA200 gap as %% of price (validated: 0.5)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='trend_min_slope_pct',
            field=models.FloatField(default=0.0, help_text='Min EMA50 slope %% over the lookback (validated: 0/off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='trend_require_adx_rising',
            field=models.BooleanField(default=False, help_text='Require 1H ADX rising (validated: off)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='trend_require_price_above_ema50',
            field=models.BooleanField(default=True, help_text='Require price on the trend side of EMA50 (validated: on)'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='trend_slope_lookback',
            field=models.PositiveIntegerField(default=3, help_text='Bars used to measure the 1H EMA50 slope'),
        ),
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='weight_structure_bonus',
            field=models.FloatField(default=0.0, help_text='Additive BOS/strong-leg confluence weight (validated: 0)'),
        ),
    ]
