# Generated by Django 4.2.10 on 2026-06-30 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0057_daytradesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytradesession',
            name='active_days',
            field=models.JSONField(blank=True, default=list, help_text='Python weekdays (0=Mon..6=Sun) this window applies to; empty = all days'),
        ),
        migrations.AlterField(
            model_name='daytradesession',
            name='end_hour',
            field=models.PositiveIntegerField(help_text='Window end hour (Nepal time, exclusive)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='daytradesession',
            name='start_hour',
            field=models.PositiveIntegerField(help_text='Window start hour (Nepal time, inclusive)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
