# Generated by Django 4.2.10 on 2026-06-30 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0058_alter_daytradesession_active_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='max_active_gw_trades',
            field=models.IntegerField(default=5, help_text="Per-trade sizing divisor: per_trade = total_trading_capital / this. Set by the rebalancer to (max_concurrent_trades + 1) so one slot's worth is held back as the reserve. NOT the concurrency cap.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='max_concurrent_trades',
            field=models.IntegerField(default=4, help_text='Maximum simultaneous open trades (the actual slot cap used by the auto-traders). Deployable capital = this x per_trade.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
