# Generated by Django 4.2.10 on 2026-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0058_alter_daytradesession_active_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestradingsettings',
            name='daytrade_live_enabled',
            field=models.BooleanField(default=True, help_text="Execute REAL Binance futures orders for day-trade signals that fire inside an active optimized Day-Trade Session. Still requires the global 'is_enabled' master switch to be ON; sized from the shared futures pool (total_trading_capital / max_active_gw_trades)."),
        ),
    ]
