# Generated by Django 4.2.10 on 2026-07-02 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0060_merge_0059_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytradestrategyconfig',
            name='signal_cooldown_minutes',
            field=models.PositiveIntegerField(default=60, help_text="After a symbol's trade closes, suppress new signals for it for this many minutes (0 = disabled)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
