# Generated by Django 4.2.10 on 2026-07-22 08:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0064_daytradepapertrade_fees_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingStrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for the 4h swing paper harness')),
                ('symbols', models.JSONField(blank=True, default=list, help_text='Symbols to scan (default: 8 majors)')),
                ('entry_timeframe', models.CharField(default='4h', max_length=5)),
                ('trend_timeframe', models.CharField(default='1d', max_length=5)),
                ('adx_min', models.FloatField(default=20.0, help_text='1D ADX floor for a confirmed trend')),
                ('breakout_lookback', models.PositiveIntegerField(default=20, help_text='Prior 4h bars for the breakout')),
                ('sl_atr_mult', models.FloatField(default=1.5)),
                ('tp_atr_mult', models.FloatField(default=3.0)),
                ('margin_per_trade', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=12)),
                ('leverage', models.IntegerField(default=10)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=Decimal('0.0004'), max_digits=8)),
                ('slippage_rate', models.DecimalField(decimal_places=6, default=Decimal('0.0002'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Swing Strategy Config',
                'verbose_name_plural': 'Swing Strategy Config',
                'db_table': 'swing_strategy_config',
            },
        ),
        migrations.CreateModel(
            name='SwingPaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('atr_at_entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=2, help_text='Margin (USDT)', max_digits=12)),
                ('leverage', models.IntegerField(default=10)),
                ('entry_time', models.DateTimeField()),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED_TP', 'Closed - Take Profit'), ('CLOSED_SL', 'Closed - Stop Loss')], db_index=True, default='OPEN', max_length=12)),
                ('profit_loss', models.DecimalField(decimal_places=8, default=0, help_text='Net of fees (USDT)', max_digits=20)),
                ('fees_paid', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Swing Paper Trade',
                'verbose_name_plural': 'Swing Paper Trades',
                'db_table': 'swing_paper_trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='swing_paper_symbol_9120dd_idx'), models.Index(fields=['status', '-created_at'], name='swing_paper_status_2e2199_idx')],
            },
        ),
    ]
