# Generated by Django 4.2.10 on 2026-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0065_swingstrategyconfig_swingpapertrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_timeframe', models.CharField(default='4h', max_length=5)),
                ('trend_timeframe', models.CharField(default='1d', max_length=5)),
                ('candle_open_time', models.DateTimeField(help_text='Open time of the 4h candle this signal belongs to')),
                ('entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('atr', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Swing Signal',
                'verbose_name_plural': 'Swing Signals',
                'db_table': 'swing_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'direction', '-created_at'], name='swing_signa_symbol_b537b8_idx'), models.Index(fields=['status', '-created_at'], name='swing_signa_status_aea794_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='swingsignal',
            constraint=models.UniqueConstraint(fields=('symbol', 'entry_timeframe', 'candle_open_time', 'direction'), name='swing_signal_dedup'),
        ),
    ]
