# Generated by Django 4.2.10 on 2026-07-22 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0066_swingsignal_swingsignal_swing_signal_dedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBlockPaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('atr_at_entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('position_size', models.DecimalField(decimal_places=2, help_text='Margin (USDT)', max_digits=12)),
                ('risk_amount', models.DecimalField(decimal_places=2, default=0, help_text='USDT risked to the stop', max_digits=14)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('leverage', models.IntegerField(default=10)),
                ('entry_time', models.DateTimeField()),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED_TP', 'Closed - Take Profit'), ('CLOSED_SL', 'Closed - Stop Loss')], db_index=True, default='OPEN', max_length=12)),
                ('profit_loss', models.DecimalField(decimal_places=8, default=0, help_text='Net of fees (USDT)', max_digits=20)),
                ('fees_paid', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Block Paper Trade',
                'verbose_name_plural': 'Order Block Paper Trades',
                'db_table': 'order_block_paper_trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderBlockStrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for the 4h order-block paper harness')),
                ('symbols', models.JSONField(blank=True, default=list, help_text='Symbols to scan (default: 12 majors)')),
                ('entry_timeframe', models.CharField(default='4h', max_length=5)),
                ('rr', models.FloatField(default=2.0, help_text='Reward:risk multiple for the fixed target')),
                ('swing_k', models.PositiveIntegerField(default=2, help_text='Swing confirmation lag (bars)')),
                ('lookback', models.PositiveIntegerField(default=10, help_text='Bars to search for the order block')),
                ('sl_buffer_atr', models.FloatField(default=0.25, help_text='ATR buffer beyond the order block')),
                ('atr_period', models.PositiveIntegerField(default=14)),
                ('account_equity', models.DecimalField(decimal_places=2, default=Decimal('10000'), help_text='Starting equity base for fixed-fractional sizing (USDT)', max_digits=14)),
                ('risk_per_trade_pct', models.FloatField(default=1.0, help_text='Percent of current equity risked per trade')),
                ('max_concurrent_positions', models.PositiveIntegerField(default=3, help_text='Cap on simultaneous open positions (correlated-exposure limit)')),
                ('leverage', models.IntegerField(default=10)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=Decimal('0.0004'), max_digits=8)),
                ('slippage_rate', models.DecimalField(decimal_places=6, default=Decimal('0.0002'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Block Strategy Config',
                'verbose_name_plural': 'Order Block Strategy Config',
                'db_table': 'order_block_strategy_config',
            },
        ),
        migrations.CreateModel(
            name='OrderBlockSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_timeframe', models.CharField(default='4h', max_length=5)),
                ('candle_open_time', models.DateTimeField(help_text='Open time of the 4h candle this signal belongs to')),
                ('entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('atr', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('structure', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXECUTED', 'Executed'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Block Signal',
                'verbose_name_plural': 'Order Block Signals',
                'db_table': 'order_block_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'direction', '-created_at'], name='order_block_symbol_f6dd0e_idx'), models.Index(fields=['status', '-created_at'], name='order_block_status_29011f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderblocksignal',
            constraint=models.UniqueConstraint(fields=('symbol', 'entry_timeframe', 'candle_open_time', 'direction'), name='order_block_signal_dedup'),
        ),
        migrations.AddIndex(
            model_name='orderblockpapertrade',
            index=models.Index(fields=['symbol', 'status'], name='order_block_symbol_6026a9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderblockpapertrade',
            index=models.Index(fields=['status', '-created_at'], name='order_block_status_4bf7e4_idx'),
        ),
    ]
