# Generated by Django 4.2.10 on 2026-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0067_orderblockpapertrade_orderblockstrategyconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderblockstrategyconfig',
            name='max_concurrent_positions',
            field=models.PositiveIntegerField(default=5, help_text='Cap on simultaneous open positions (correlated-exposure limit)'),
        ),
    ]
