# Generated by Django 4.2.10 on 2026-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0068_alter_orderblockstrategyconfig_max_concurrent_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestradingsettings',
            name='daytrade_max_trades_per_session',
            field=models.PositiveIntegerField(default=2, help_text='Max REAL day-trade futures entries opened per active Day-Trade Session window (per day). 0 = unlimited. Guards against over-trading live.'),
        ),
    ]
