# Generated by Django 4.2.10 on 2026-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0069_futurestradingsettings_daytrade_max_trades_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestradingsettings',
            name='consecutive_sl_halt_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Circuit breaker for ALL live bots: after this many consecutive stop-losses (pooled, since the last take-profit) within the active Day-Trade Session window, block new live futures entries until a take-profit resets it. 0 = disabled.'),
        ),
    ]
