# Generated by Django 4.2.10 on 2026-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0070_futurestradingsettings_consecutive_sl_halt_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurestradingsettings',
            name='daytrade_max_trades_per_session',
        ),
        migrations.AlterField(
            model_name='futurestradingsettings',
            name='consecutive_sl_halt_threshold',
            field=models.PositiveIntegerField(default=2, help_text="Circuit breaker (per engine): after this many consecutive stop-losses since the last take-profit within the engine's active trading-session window, block that engine's new live futures entries until a take-profit resets it. Validated optimum is 2 (forward-tested). 0 = disabled."),
        ),
    ]
